---
abstract: 'per-request container '
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Scope-Container
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Plack::Middleware::Scope::Container:
    file: lib/Plack/Middleware/Scope/Container.pm
    version: 0.04
requires:
  Plack: 0.9982
  Scope::Container: 0.03
  parent: 0
resources:
  bugtracker: https://github.com/kazeburo/Plack-Middleware-Scope-Container/issues
  homepage: https://github.com/kazeburo/Plack-Middleware-Scope-Container
  repository: git://github.com/kazeburo/Plack-Middleware-Scope-Container.git
version: 0.04
x_contributors:
  - 'motemen <motemen@gmail.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
